export const countries = [
  { name: "Brasil", code: "55" },
  { name: "Afeganistão", code: "93" },
  { name: "África do Sul", code: "27" },
  { name: "Albânia", code: "355" },
  { name: "Alemanha", code: "49" },
  { name: "Andorra", code: "376" },
  { name: "Angola", code: "244" },
  { name: "Arábia Saudita", code: "966" },
  { name: "Argélia", code: "213" },
  { name: "Argentina", code: "54" },
  { name: "Armênia", code: "374" },
  { name: "Austrália", code: "61" },
  { name: "Áustria", code: "43" },
  { name: "Azerbaijão", code: "994" },
  { name: "Bahamas", code: "1242" },
  { name: "Bangladesh", code: "880" },
  { name: "Barbados", code: "1246" },
  { name: "Barein", code: "973" },
  { name: "Bélgica", code: "32" },
  { name: "Belize", code: "501" },
  { name: "Benin", code: "229" },
  { name: "Bielorrússia", code: "375" },
  { name: "Bolívia", code: "591" },
  { name: "Bósnia e Herzegovina", code: "387" },
  { name: "Botsuana", code: "267" },
  { name: "Brunei", code: "673" },
  { name: "Bulgária", code: "359" },
  { name: "Burkina Faso", code: "226" },
  { name: "Burundi", code: "257" },
  { name: "Butão", code: "975" },
  { name: "Cabo Verde", code: "238" },
  { name: "Camarões", code: "237" },
  { name: "Camboja", code: "855" },
  { name: "Canadá", code: "1" },
  { name: "Catar", code: "974" },
  { name: "Cazaquistão", code: "7" },
  { name: "Chade", code: "235" },
  { name: "Chile", code: "56" },
  { name: "China", code: "86" },
  { name: "Chipre", code: "357" },
  { name: "Colômbia", code: "57" },
  { name: "Comores", code: "269" },
  { name: "Congo", code: "242" },
  { name: "Coreia do Norte", code: "850" },
  { name: "Coreia do Sul", code: "82" },
  { name: "Costa do Marfim", code: "225" },
  { name: "Costa Rica", code: "506" },
  { name: "Croácia", code: "385" },
  { name: "Cuba", code: "53" },
  { name: "Dinamarca", code: "45" },
  { name: "Djibuti", code: "253" },
  { name: "Dominica", code: "1767" },
  { name: "Egito", code: "20" },
  { name: "El Salvador", code: "503" },
  { name: "Emirados Árabes Unidos", code: "971" },
  { name: "Equador", code: "593" },
  { name: "Eritreia", code: "291" },
  { name: "Eslováquia", code: "421" },
  { name: "Eslovênia", code: "386" },
  { name: "Espanha", code: "34" },
  { name: "Estados Unidos", code: "1" },
  { name: "Estônia", code: "372" },
  { name: "Etiópia", code: "251" },
  { name: "Fiji", code: "679" },
  { name: "Filipinas", code: "63" },
  { name: "Finlândia", code: "358" },
  { name: "França", code: "33" },
  { name: "Gabão", code: "241" },
  { name: "Gâmbia", code: "220" },
  { name: "Gana", code: "233" },
  { name: "Geórgia", code: "995" },
  { name: "Granada", code: "1473" },
  { name: "Grécia", code: "30" },
  { name: "Guatemala", code: "502" },
  { name: "Guiana", code: "592" },
  { name: "Guiné", code: "224" },
  { name: "Guiné-Bissau", code: "245" },
  { name: "Guiné Equatorial", code: "240" },
  { name: "Haiti", code: "509" },
  { name: "Honduras", code: "504" },
  { name: "Hungria", code: "36" },
  { name: "Iêmen", code: "967" },
  { name: "Índia", code: "91" },
  { name: "Indonésia", code: "62" },
  { name: "Irã", code: "98" },
  { name: "Iraque", code: "964" },
  { name: "Irlanda", code: "353" },
  { name: "Islândia", code: "354" },
  { name: "Israel", code: "972" },
  { name: "Itália", code: "39" },
  { name: "Jamaica", code: "1876" },
  { name: "Japão", code: "81" },
  { name: "Jordânia", code: "962" },
  { name: "Kuwait", code: "965" },
  { name: "Laos", code: "856" },
  { name: "Letônia", code: "371" },
  { name: "Líbano", code: "961" },
  { name: "Libéria", code: "231" },
  { name: "Líbia", code: "218" },
  { name: "Liechtenstein", code: "423" },
  { name: "Lituânia", code: "370" },
  { name: "Luxemburgo", code: "352" },
  { name: "Macedônia do Norte", code: "389" },
  { name: "Madagascar", code: "261" },
  { name: "Malásia", code: "60" },
  { name: "Malawi", code: "265" },
  { name: "Maldivas", code: "960" },
  { name: "Mali", code: "223" },
  { name: "Malta", code: "356" },
  { name: "Marrocos", code: "212" },
  { name: "Maurício", code: "230" },
  { name: "Mauritânia", code: "222" },
  { name: "México", code: "52" },
  { name: "Moçambique", code: "258" },
  { name: "Moldávia", code: "373" },
  { name: "Mônaco", code: "377" },
  { name: "Mongólia", code: "976" },
  { name: "Montenegro", code: "382" },
  { name: "Namíbia", code: "264" },
  { name: "Nepal", code: "977" },
  { name: "Nicarágua", code: "505" },
  { name: "Níger", code: "227" },
  { name: "Nigéria", code: "234" },
  { name: "Noruega", code: "47" },
  { name: "Nova Zelândia", code: "64" },
  { name: "Omã", code: "968" },
  { name: "Países Baixos", code: "31" },
  { name: "Paquistão", code: "92" },
  { name: "Panamá", code: "507" },
  { name: "Papua Nova Guiné", code: "675" },
  { name: "Paraguai", code: "595" },
  { name: "Peru", code: "51" },
  { name: "Polônia", code: "48" },
  { name: "Portugal", code: "351" },
  { name: "Quênia", code: "254" },
  { name: "Quirguistão", code: "996" },
  { name: "Reino Unido", code: "44" },
  { name: "República Centro-Africana", code: "236" },
  { name: "República Checa", code: "420" },
  { name: "República Democrática do Congo", code: "243" },
  { name: "República Dominicana", code: "1809" },
  { name: "Romênia", code: "40" },
  { name: "Ruanda", code: "250" },
  { name: "Rússia", code: "7" },
  { name: "Senegal", code: "221" },
  { name: "Serra Leoa", code: "232" },
  { name: "Sérvia", code: "381" },
  { name: "Singapura", code: "65" },
  { name: "Síria", code: "963" },
  { name: "Somália", code: "252" },
  { name: "Sri Lanka", code: "94" },
  { name: "Sudão", code: "249" },
  { name: "Suécia", code: "46" },
  { name: "Suíça", code: "41" },
  { name: "Suriname", code: "597" },
  { name: "Tailândia", code: "66" },
  { name: "Taiwan", code: "886" },
  { name: "Tajiquistão", code: "992" },
  { name: "Tanzânia", code: "255" },
  { name: "Timor-Leste", code: "670" },
  { name: "Togo", code: "228" },
  { name: "Tunísia", code: "216" },
  { name: "Turquia", code: "90" },
  { name: "Turcomenistão", code: "993" },
  { name: "Ucrânia", code: "380" },
  { name: "Uganda", code: "256" },
  { name: "Uruguai", code: "598" },
  { name: "Uzbequistão", code: "998" },
  { name: "Vanuatu", code: "678" },
  { name: "Vaticano", code: "379" },
  { name: "Venezuela", code: "58" },
  { name: "Vietnã", code: "84" },
  { name: "Zâmbia", code: "260" },
  { name: "Zimbábue", code: "263" }
];